name: Scan images in Lacework

on: workflow_dispatch
strategy:
  matrix:
    image: [detcaccounts/resultsapp, detcaccounts/voteapp, detcaccounts/worker]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Scan container images for vulnerabitilies using Lacework
        uses: timarenz/lw-scanner-action@v0.3.0
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
          LW_SCANNER_SAVE_RESULTS: true
        with:
          image_name: ${{ matrix.image }}
          image_tag: latest
